
name: Installation and testing
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # First day of the month

jobs:
  run:
    name: Installation on (${{ matrix.os }} with Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow --tags
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        pip3 install packaging
    - name: Install package
      run: |
        pip install -r requirements-dev.txt
        pip install -U -e .
    - name: Test module load
      run: python -c "import ndx_turner_metadata"
    - name: Run tests
      run: |
        pytest -v
